---
language: go

go:
  - 1.8.x
  - tip

branches:
  only:
    - master
    - /^travis.*/
    - /^v.*/

stages:
  - name: test

jobs:
  include:
    - stage: test
      before_install:
        - go get -t -v ./...
        - chmod +x ./test.sh
      script:
        - ./test.sh
      after_success: bash <(curl -s https://codecov.io/bash)
